name: release

on:
  push:
    tags: [ "*" ]

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:

  release:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - "3.9"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0} # needed for conda

    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2.5
      with:
        # TODO: update to 1.13.3 and later
        version: 1.13.2       # The version of PDM to install. Leave it as empty to use the latest version from PyPI
        prerelease: false     # Allow prerelease versions to be installed
        enable-pep582: false  # Enable PEP 582 package loading globally
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pdm install -G duty -G tests

    - name: Bundle venv and dist
      # TODO: migrate to `pdm config python.use_venv true` when pdm-venv has a new release which matches pdm 1.13.3 changes
      # see https://pdm.fming.dev/configuration/
      run: |
        pdm config use_venv true
        VERSION=$(echo ${GITHUB_REF_NAME})
        make release VERSION=${VERSION}
