name: ci

on:
  push:
    tags: [ "*" ]

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:

  release:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - "3.9"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2.5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pdm install -G duty -G tests

    - name: Bundle venv and dist
      run: >
        IFS=- read VERSION <<< $(echo ${GITHUB_REF} | cut -d'/' -f 3)
        make release VERSION=${VERSION}
